name: zuachat
description: Application Flutter ZuaChat
publish_to: "none"

version: 3.0.0+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  # ðŸŒ Internationalisation
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  dio: ^5.4.0
  shared_preferences: ^2.5.3
  record: ^6.1.2
  cached_network_image: ^3.3.1
  image_picker: ^1.2.0
  file_picker: ^8.0.0
  fluttertoast: ^8.2.4
  url_launcher: ^6.3.0
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  image_gallery_saver_plus: ^4.0.1
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  video_compress: ^3.1.2
  video_player: ^2.10.1
  wakelock_plus: ^1.4.0
  video_thumbnail: ^0.5.6
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/categories.json
    - assets/pays.json
    - assets/sounds/beep.mp3
    - assets/sounds/pop.mp3
    - assets/sounds/like.mp3
    - assets/default-avatar.png
    - assets/logo2.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
